<a href="https://colab.research.google.com/github/tanjiro040/Data-Engineering-and-Analytics/blob/main/DE_LAB4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vectors and Matrices for Data Analysis**
**(using Numpy python Library)**

In [ ]:
#1. Calculating DISPLACEMENT

'''A person walks from origin 0 (0,0) to point A (1,2) to point B(2,1).
Calculate the distance and displacement between location points  O and B'''

import numpy as np
import cmath

O = np.array([0,0]) # position vector for location O
A = np.array([2,1]) # position vector for location A
B = np.array([3,3]) # position vector for location B

OA = A-O   # distance vector between O and A
AB = B-A   # distance vector between A and B

OAmag=np.linalg.norm(OA) # length of vector OA
print("Distance travelled from O to A =", OAmag)
ABmag=np.linalg.norm(AB) # length of vector AB
print("Distance travelled from A to B =",ABmag)

OB=OA+AB  # Displacement vector from O to B
print("Net Displacement= ",OB)

OBmag=np.linalg.norm(OB) # length of vector OA
print("Magnitude of Displacement:",OBmag)

OBangle_RAD=np.angle(complex(OB[0],OB[1])) # calculating phase angle = tan-1(y/x)=  tan-1(OB[1]/OB[0])
OBangle_DEG=np.degrees(OBangle_RAD)
print("Angle made by Displacement Vector w.r.t x axis:",OBangle_DEG)

Distance travelled from O to A = 2.23606797749979
Distance travelled from A to B = 2.23606797749979
Net Displacement=  [3 3]
Magnitude of Displacement: 4.242640687119285
Angle made by Displacement Vector w.r.t x axis: 45.0


In [ ]:
#2 To calculate of DOT PRODUCT (SCALAR PRODUCT) of TWO VECTORS

''' Calculate the dot product for the given two vectors
                    A = 1+1j
                    B = 2+3j
    A*B = |A||B|cos(theta) '''

VectorA = [1,1]  # Representing vector A as a 1x2 array
VectorB = [2,3]  # Representing vector B as a 1x2 array

MagA=np.linalg.norm(VectorA)
print("Magnitude of A = ",MagA)

MagB=np.linalg.norm(VectorB)
print("Magnitude of B = ",MagB)

AdotB= np.dot(VectorA,VectorB) # Determining the DOT product (A * B)using the dot function

COSangleAB=AdotB/(MagA*MagB) # cos(thetha) = A*B/|A||B|

AngleAB_Radians= np.arccos(COSangleAB) # Angle between A and B = cos-1( A*B/|A||B|)
AngleAB_Degrees=np.degrees(AngleAB_Radians)# Coverting angle in degrees

print("DOT product of vectors A and B = ", AdotB)
print("Angle between vectors A and B = ", AngleAB_Degrees)

Magnitude of A =  1.4142135623730951
Magnitude of B =  3.605551275463989
DOT product of vectors A and B =  5
Angle between vectors A and B =  11.309932474020261


In [ ]:
#3 To calculate of CROSS PRODUCT (VECTOR PRODUCT) of TWO VECTORS

''' Calculate the CROSS product for the given two vectors
                    A = 1+1j
                    B = 2+3j
    AxB = |A||B|sin(theta) '''

VectorA = np.array([1,1])  # Representing vector A as a 1x2 array
VectorB = np.array([2,3])  # Representing vector B as a 1x2 array

MagA=np.linalg.norm(VectorA)
print("Magnitude of A = ",MagA)

MagB=np.linalg.norm(VectorB)
print("Magnitude of B = ",MagB)

AcrossB= np.array([VectorA[0]*VectorB[1],-VectorA[1]*VectorB[0]])
print("CROSS product of vectors A and B = ", AcrossB)

Magnitude of A =  1.4142135623730951
Magnitude of B =  3.605551275463989
CROSS product of vectors A and B =  [ 3 -2]


In [ ]:
#4 Addition of two vectors A and B

import math

VectorA = np.array([1,1])  # Representing vector A as a 1x2 array
VectorB = np.array([2,3])  # Representing vector B as a 1x2 array

MagA=np.linalg.norm(VectorA)
print("Magnitude of A = ",MagA)

MagB=np.linalg.norm(VectorB)
print("Magnitude of B = ",MagB)

AdotB= np.dot(VectorA,VectorB) # Determining the DOT product (A * B)using the dot function

COSangleAB=AdotB/(MagA*MagB) # cos(thetha) = A*B/|A||B|

AngleAB_Radians= np.arccos(COSangleAB) # Angle between A and B = cos-1( A*B/|A||B|)

A2=MagA**2
B2=MagB**2
COSAB=math.cos(AngleAB_Radians)
SINAB=math.sin(AngleAB_Radians)
ADDmag=math.sqrt(A2+B2+(2*MagA*MagB*COSAB))
ADDangle=np.arctan((MagA*SINAB)/(MagA+(MagB*COSAB)))
ADDangle_Degrees=np.degrees(ADDangle)
print("Magnitude of A+B = ",ADDmag)
print("Angle of A+B w.r.t. A",ADDangle_Degrees)

Magnitude of A =  1.4142135623730951
Magnitude of B =  3.605551275463989
Magnitude of A+B =  5.0
Angle of A+B w.r.t. A 3.207111142186431


**Other operations with Vectors and Matrices using Numpy**

In [ ]:
#5 Concatenation of two ROW VECTORs (1xn) MATRICES

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#6 Concatenation of two (nxn) MATRICES

import numpy as np

arr1 = np.array([[1, 2, 3],[7, 8, 9]])

arr2 = np.array([[4, 5,6], [10,11,12]])

arr = np.concatenate((arr1, arr2))

print(arr)

[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [ ]:
#7 Combining the two arrays column wise using stack

import numpy as np

arr1 = np.array([1, 2, 3])
print("Array1\n", arr1)

arr2 = np.array([4, 5, 6])
print("Array2\n", arr2)

print("Combined Array (STACKED COLUMN-WISE)\n")
arr = np.stack((arr1, arr2), axis=1)

print(arr)

Array1
 [1 2 3]
Array2
 [4 5 6]
Combined Array (STACKED COLUMN-WISE)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#8 Combining the two arrays ROW wise using stack

import numpy as np

arr1 = np.array([1, 2, 3])
print("Array1\n", arr1)

arr2 = np.array([4, 5, 6])
print("Array2\n", arr2)

print("Combined Array (STACKED ROW-WISE)\n")
arr = np.stack((arr1, arr2), axis=0)

print(arr)

Array1
 [1 2 3]
Array2
 [4 5 6]
Combined Array (STACKED ROW-WISE)

[[1 2 3]
 [4 5 6]]


In [ ]:
#9 Combining(STACKING) two arrays HORIZONTALLY (ROW-WISE) using hstack

import numpy as np

arr1 = np.array([1, 2, 3])
print("Array1\n", arr1)

arr2 = np.array([4, 5, 6])
print("Array2\n", arr2)

print("Combined Array (STACKED HORIZONTALLY)\n")
arr = np.hstack((arr1, arr2))

print(arr)

Array1
 [1 2 3]
Array2
 [4 5 6]
Combined Array (STACKED HORIZONTALLY)

[1 2 3 4 5 6]


In [ ]:
#10 Combining(STACKING) two arrays VERTICALLY using vstack

import numpy as np

arr1 = np.array([1, 2, 3])
print("Array1\n", arr1)

arr2 = np.array([4, 5, 6])
print("Array2\n", arr2)

print("Combined Array (STACKED VERTICALLY)\n")
arr = np.vstack((arr1, arr2))

print(arr)

Array1
 [1 2 3]
Array2
 [4 5 6]
Combined Array (STACKED VERTICALLY)

[[1 2 3]
 [4 5 6]]


In [ ]:
#11 ARRAY SPLITTING (Example 1)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print("Original Array:\n",arr)

newarr = np.array_split(arr, 3) # Splitting original array into three parts

print("NEW ARRAY\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])

Original Array:
 [1 2 3 4 5 6]
NEW ARRAY

[1 2]
[3 4]
[5 6]


In [ ]:
#12 ARRAY SPLITTING (Example 2)

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print("Original Array:\n",arr)

newarr = np.array_split(arr, 3)# Splitting original array into three parts

print("NEW ARRAY\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])

Original Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
NEW ARRAY

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [ ]:
#13 ARRAY SPLITTING (Example 3)

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print("Original Array:\n",arr)

print("NEW ARRAY\n")
newarr = np.vsplit(arr, 2)

print(newarr[0])
print(newarr[1])

Original Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
NEW ARRAY

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
#14 ARRAY SPLITTING (Example 4)

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6,7,8]])
print("Original Array:\n",arr)

print("NEW ARRAY\n")
newarr = np.hsplit(arr, 2)

print(newarr[0])
print(newarr[1])

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
NEW ARRAY

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [ ]:
#15 Extracting the index (position) of the desired element in an array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 1, 4])
print("Original Array:\n",arr)

x = np.where(arr == 1)

print("location of element '1'in the array\n",x)

Original Array:
 [1 2 3 4 5 1 4]
location of element '1'in the array
 (array([0, 5]),)


In [ ]:
#16 Extracting the index (position) of the desired element in an array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 1, 4])
print("Original Array:\n",arr)

x = np.where(arr%2==0)
print("location of even elements in the array\n",x)

Original Array:
 [1 2 3 4 5 1 4]
location of even elements in the array
 (array([1, 3, 6]),)


In [ ]:
#17 Displaying even elements in an array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 1, 4])

for n in arr:
  if n%2==0:
    print(n)

2
4
4


In [ ]:
#18 SORT the elements of an array in ASCENDING ORDER using sort() function

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
#19 SORT the elements of an array in DESCENDING ORDER using sort() function

import numpy as np

arr = np.array([3, 2, 0, 1])

arr1= np.sort(arr)
arr2= np.flip(arr1) # reversing array sorted in ascending order

print(arr2)

[3 2 1 0]


In [ ]:
#20 SORT the elements of an array of strings in ASCENDING ORDER using sort() function

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
#21 SORT elements in each ROW of a 2D matrix in ASCENDING ORDER using sort() function

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


**Some more matrix (2D Array) operations in Numpy**

In [ ]:
# Transpose of a Matrix

A = np.array([[4,3],[3,2]])
print("Original Matrix\n",A)

A_Transpose= A.transpose()
print("Matrix TRanspose\n",A_Transpose)

Original Matrix
 [[4 3]
 [3 2]]
Matrix TRanspose
 [[4 3]
 [3 2]]


In [ ]:
# Inverse and Invertibility of a Matrix

''' A square matrix 'A' of size (nxn) is said to be INVERTIBLE,
if there exists an inverse matrix B such that
        AB= I
 where, B = Inverse(A)= A
        I = Identity matrix

Find Inverse of A =[[4,3],[3,2]]'''

A = np.array([[4,3],[3,2]])
print("Original Matrix\n",A)

A_Inverse= np.linalg.inv(A)
print("Original Matrix\n",A_Inverse)


Original Matrix
 [[4 3]
 [3 2]]
Original Matrix
 [[-2.  3.]
 [ 3. -4.]]


In [ ]:
# Solving a system of linear equations

''' 4x-2y =  20
   -5x-5y = -10 '''

A = np.array([[4,-2],[-5,-5]])
B = np.array([20,-10])

Ainverse= np.linalg.inv(A)
X = np.dot(Ainverse,B)

print(X)

[ 4. -2.]


In [ ]:
# Square root of Array

arr = np.array([1, 2, 3, 4, 5])
arr_sqrt=np.sqrt(arr)
print("\nSquare root of Array1 elements: ")
print(arr_sqrt)


Square root of Array1 elements: 
[1.         1.41421356 1.73205081 2.         2.23606798]
