<a href="https://colab.research.google.com/github/tanjiro040/Data-Engineering-and-Analytics/blob/main/DE_Lab3_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creating a 1D matrix (vector) using array()

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
# Creating a 2D matrix using an array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Creating a 3D matrix using an array

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# To determine the size (dimension) of a mtrix using ndim

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [ ]:
# Accesssing individual elements of an array

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
# Accesssing individual elements of an array

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)
print('5th element in 2nd row: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element in 2nd row:  10


In [ ]:
# Accesssing individual elements of an array

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("2D array created is\n")
print(arr)

print("\nElements from second row (index 1) and columns(with index 1 to 3)\n")
print(arr[1, 1:4])

2D array created is

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Elements from second row (index 1) and columns(with index 1 to 3)

[7 8 9]


In [ ]:
# Make a copy of original array,change the original array and display both arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print("Original Array")
print(arr)
print("Modified Array")
print(x)

Original Array
[42  2  3  4  5]
Modified Array
[1 2 3 4 5]


In [ ]:
# Make a view of the original array, change the original array, and display both arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view() # create view of 'arr' and store it in 'x'
arr[0] = 42

print("Array 'arr'")
print(arr)
print("Array 'x'")
print(x)

Array 'arr'
[42  2  3  4  5]
Array 'x'
[42  2  3  4  5]


In [ ]:
# Make a view of the original array, change the original array, and display both arrays

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view() # create view of 'arr' and store it in 'x'
x[1] = 22

print("Array 'arr'")
print(arr)
print("Array 'x'")
print(x)

Array 'arr'
[ 1 22  3  4  5]
Array 'x'
[ 1 22  3  4  5]


In [ ]:
# Print the shape of a 2-D array

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("(ROWs,COLUMNs) of the given 2-D array is")
print(arr.shape)

(ROWs,COLUMNs) of the given 2-D array is
(2, 4)


In [ ]:
# Converting a 1-D array with 12 elements into a 2-D array of size (4x3)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print("Original array",arr)

newarr = arr.reshape(4, 3)
print("\n2-D array reshaped in 4 Rows and 3 Columns\n")
print(newarr)


Original array [ 1  2  3  4  5  6  7  8  9 10 11 12]

2-D array reshaped in 4 Rows and 3 Columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# To determine DETERMINANT of a matrix

import numpy as np

arr = np.array([[1, 2],[4, 5]])
print("The given matrix is\n", arr)

DET=np.linalg.det(arr)

print("DETERMINANT of the matrix is ",DET)


The given matrix is
 [[1 2]
 [4 5]]
DETERMINANT of the matrix is  -2.9999999999999996


In [ ]:
# To determine RANK of a matrix

import numpy as np

arr = np.array([[1, 2, 1],[3, 4, 7],[3, 6, 3]])
print("The given matrix is\n", arr)

RANK=np.linalg.matrix_rank(arr)

print("RANK of the matrix is ",RANK)


The given matrix is
 [[1 2 1]
 [3 4 7]
 [3 6 3]]
RANK of the matrix is  2


In [ ]:
# To determine Nullity of a matrix

# using RANK-Nullity Theorem
# Total No. of columns = RANK + Nullity
# EXAMPLE 1

import numpy as np

arr = np.array([[1, 2, 1],[3, 4, 7],[3, 6, 3]])
print("The given matrix is\n", arr)

RANK=np.linalg.matrix_rank(arr)  # Rank of 2-D matrix, 'arr'

COLUMNs=arr.shape[1] # No. of columns in 2-D matrix, 'arr'

print("Rank of the given matrix is ", RANK)
print("Nullity of the given matrix is ", COLUMNs-RANK)

The given matrix is
 [[1 2 1]
 [3 4 7]
 [3 6 3]]
Rank of the given matrix is  2
Nullity of the given matrix is  1


In [ ]:
# To ADD and SUBTRACT two matrices

import numpy as np

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([[2, 4, 6, 8], [1, 1, 6, 3]])

print("MATRIX 1 + MATRIX 2\n",arr1+arr2)
print("MATRIX 1 - MATRIX 2\n",arr1-arr2)


MATRIX 1 + MATRIX 2
 [[ 3  6  9 12]
 [ 6  7 13 11]]
MATRIX 1 - MATRIX 2
 [[-1 -2 -3 -4]
 [ 4  5  1  5]]


In [ ]:
# To multiply two matrices using dot() function

import numpy as np

arr1 = np.array([[1, 2], [5, 6]]) # Matrix 1
arr2 = np.array([[2, 4], [1, 1]]) # Matrix 2

arr3=np.dot(arr1,arr2)

print('Multiplication of Matrix 1 and Matrix 2')
print(arr3)

Multiplication of Matrix 1 and Matrix 2
[[ 4  6]
 [16 26]]


In [ ]:
# To multiply a vector (1D array) with a matrix using dot() and transpose() function

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([[2, 4, 6, 8]])
arr2t=arr2.transpose()
arr3=np.dot(arr1,arr2t)
print(arr3)

[[ 60]
 [140]]
