<a href="https://colab.research.google.com/github/tanjiro040/Data-Engineering-and-Analytics/blob/main/kanchan_sharma_AE_319_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating a 3D matrix (vector) using array()
import numpy as np
arrA=np.array([[-5,2,-3],[6,0,2],[2,6,1]])
arrB=np.array([[2,4,5],[-8,10,3],[-2,-3,-9]])
print(arrA)
print(arrB)

[[-5  2 -3]
 [ 6  0  2]
 [ 2  6  1]]
[[ 2  4  5]
 [-8 10  3]
 [-2 -3 -9]]


In [ ]:
#determine the DETERMINANT of the matrix
import numpy as np
arrA=np.array([[-5,1,-3],[6,0,2],[2,6,1]])
arrB=np.array([[2,4,5],[-8,10,3],[-2,-3,-9]])
print("Matrix A is\n",arrA)
print("Matrix B is\n",arrB)
DETA=np.linalg.det(arrA)
DETB=np.linalg.det(arrB)
print("Determinant of the matrix A is",DETA)
print("Determinant of the matrix B is",DETB)

Matrix A is
 [[-5  1 -3]
 [ 6  0  2]
 [ 2  6  1]]
Matrix B is
 [[ 2  4  5]
 [-8 10  3]
 [-2 -3 -9]]
Determinant of the matrix A is -49.99999999999999
Determinant of the matrix B is -254.0


In [ ]:
#determine the rank of the matrix
import numpy as np
arr1=np.array([[0,0,0,0],[4,2,3,0],[1,0,0,0],[4,0,3,0]])
arr2=np.array([[5,4,7],[5,-6,5],[4,2,-3]])
arr3=np.array([[1,0,1],[2,1,0],[0,-1,2]])
arr4=np.array([[1,1,1],[3,4,-1],[-1,-2,5]])
arr5=np.array([[1,3,4],[3,9,12],[1,3,4]])
print("Matrix 1 is\n",arr1)
print("Matrix 2 is\n",arr2)
print("Matrix 3 is\n",arr3)
print("Matrix 4 is\n",arr4)
print("Matrix 5 is\n",arr5)
rank1=np.linalg.matrix_rank(arr1)
rank2=np.linalg.matrix_rank(arr2)
rank3=np.linalg.matrix_rank(arr3)
rank4=np.linalg.matrix_rank(arr4)
RANK5=np.linalg.matrix_rank(arr5)
print("Rank of the 1st matrix is",rank1)
print("Rank of the 2nd matrix is",rank2)
print("Rank of the 3rd matrix is",rank3)
print("Rank of the 4th matrix is",rank4)
print("Rank of the 5th matrix is",RANK5)

Matrix 1 is
 [[0 0 0 0]
 [4 2 3 0]
 [1 0 0 0]
 [4 0 3 0]]
Matrix 2 is
 [[ 5  4  7]
 [ 5 -6  5]
 [ 4  2 -3]]
Matrix 3 is
 [[ 1  0  1]
 [ 2  1  0]
 [ 0 -1  2]]
Matrix 4 is
 [[ 1  1  1]
 [ 3  4 -1]
 [-1 -2  5]]
Matrix 5 is
 [[ 1  3  4]
 [ 3  9 12]
 [ 1  3  4]]
Rank of the 1st matrix is 3
Rank of the 2nd matrix is 3
Rank of the 3rd matrix is 2
Rank of the 4th matrix is 3
Rank of the 5th matrix is 1


In [ ]:
#TO ADD AND SUB TWO MATRICES
import numpy as np
arrA=np.array([[-5,1,-3],[6,0,2],[2,6,1]])
arrB=np.array([[2,4,5],[-8,10,3],[-2,-3,-9]])
print(arrA+arrB)
print(arrA-arrB)

[[-3  5  2]
 [-2 10  5]
 [ 0  3 -8]]
[[ -7  -3  -8]
 [ 14 -10  -1]
 [  4   9  10]]


In [ ]:
#TO multipy TWO MATRICES
import numpy as np
arrA=np.array([[-5,1,-3],[6,0,2],[2,6,1]])
arrB=np.array([[2,4,5],[8,10,3],[-2,-3,-9]])
arrC=np.dot(arrA,arrB)
print(arrC)

[[ 4 -1  5]
 [ 8 18 12]
 [50 65 19]]


In [ ]:
#determine the nullity of the matrix
import numpy as np
arr1=np.array([[0,0,0,0],[4,2,3,0],[1,0,0,0],[4,0,3,0]])
arr2=np.array([[5,4,7],[5,-6,5],[4,2,-3]])
arr3=np.array([[1,0,1],[2,1,0],[0,-1,2]])
arr4=np.array([[1,1,1],[3,4,-1],[-1,-2,5]])
arr5=np.array([[1,3,4],[3,9,12],[1,3,4]])
print(" Matrix 1 is\n",arr1)
print("Matrix 2 is\n",arr2)
print("Matrix 3 is\n",arr3)
print("Matrix 4 is\n",arr4)
print("Matrix 5 is\n",arr5)
rank1=np.linalg.matrix_rank(arr1)
column1=arr1.shape[1]
rank2=np.linalg.matrix_rank(arr2)
column2=arr2.shape[1]
rank3=np.linalg.matrix_rank(arr3)
column3=arr3.shape[1]
rank4=np.linalg.matrix_rank(arr4)
column4=arr4.shape[1]
RANK5=np.linalg.matrix_rank(arr5)
column5=arr5.shape[1]
print("Rank of the 1st matrix is",rank1)
print("Nullity of the 1st matrix is",column1-rank1)
print("Rank of the 2nd matrix is",rank2)
print("Nullity of the 2nd matrix is",column2-rank2)
print("Rank of the 3rd matrix is",rank3)
print("Nullity of the 3rd matrix is",column3-rank3)
print("Rank of the 4th matrix is",rank4)
print("Nullity of the 4th matrix is",column4-rank4)
print("Rank of the 5th matrix is",RANK5)
print("Nullity of the 5th matrix is",column5-RANK5)

 Matrix 1 is
 [[0 0 0 0]
 [4 2 3 0]
 [1 0 0 0]
 [4 0 3 0]]
Matrix 2 is
 [[ 5  4  7]
 [ 5 -6  5]
 [ 4  2 -3]]
Matrix 3 is
 [[ 1  0  1]
 [ 2  1  0]
 [ 0 -1  2]]
Matrix 4 is
 [[ 1  1  1]
 [ 3  4 -1]
 [-1 -2  5]]
Matrix 5 is
 [[ 1  3  4]
 [ 3  9 12]
 [ 1  3  4]]
Rank of the 1st matrix is 3
Nullity of the 1st matrix is 1
Rank of the 2nd matrix is 3
Nullity of the 2nd matrix is 0
Rank of the 3rd matrix is 2
Nullity of the 3rd matrix is 1
Rank of the 4th matrix is 3
Nullity of the 4th matrix is 0
Rank of the 5th matrix is 1
Nullity of the 5th matrix is 2
